plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - "vendor/**/*"
    - "coverage/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

RSpec/MultipleExpectations:
  Max: 3

RSpec/SpecFilePathFormat:
  Enabled: false
